# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3CVu2imaIe_D5M_mrqM78FZH2qbYS5P
"""

first_number=10
second_number=2
multiply=first_number* second_number
print(f"The multiply btween {first_number} and {second_number} is {multiply}")

num1 = 10
num2 = 20
print(num1 == num2)
print(num1 != num2)

number = 150
print(number > 100)

str1 = "Hello"
str2 = "Guys"
print(len(str1) == len(str2))
print(len(str1) > len(str2))
print(len(str1) < len(str2))

age = 21
print(age >= 18)

a, b, c = 5, 10, 15
print(a < b < c)
print(c > b > a)
print(a > c)

num1, num2, num3 = 10, 20, 30
average = (num1 + num2 + num3) / 3
print(average)

power = 2 ** 5
print(power)

remainder = 50 % 7
print(remainder)

floor_div = 25 // 4
print(floor_div)

first_number=2
second_number=4
sum=first_number+second_number
difference=first_number-second_number
product=first_number*second_number
print(f"The sum of First number and Second number is {sum} and Difference of First number and second number is {difference} and product of First number and Second number is {product}")

celsius = 25
fahrenheit = celsius * 9/5 + 32
print(fahrenheit)

result=(10 + 5) * 2 - 3
print(f"The result of this expression is {result}")

width=34
height=27
Area_of_rectangle=width*height
print(f"The area of rectangle is {Area_of_rectangle}")

first_name="Rasikh"
second_name="Ali"
full_name=first_name + " " + second_name
print(f"My Full name is {full_name}")